### ISSUE TITLE
What about tools about Front-End quality?

### ISSUE THREAD

**Issue by borisschapira** [thedaviddias/Resources-Front-End-Beginner#12]
Thanks for the hard work compiling all the resources. Have you considered adding some audit tools?

* Accessibility: tanaguru, asquatasun, …
* Global quality: opquast
* Performance: dareboost, gtmetrix, …
* Security (yep, even on the front-end)

**Comment by thedaviddias** [comment]
Hi @borisschapira, indeed these tools are not present in the beginner checklist... I put them in another checklist I'm working on for "after beginner".

I wanted to have a first simple list of really small basics.

More is coming! Thanks to point that out.

**Comment by borisschapira** [comment]
I'm eager to see and/or contribute to this other list. Keep us informed!

**Comment by thedaviddias** [comment]
Dans une petite semaine c'est promis @borisschapira :D
