### ISSUE TITLE
Add Codrops Collective to the Newsletters section?

### ISSUE THREAD

**Issue by botelho** [thedaviddias/Resources-Front-End-Beginner#5]
https://tympanus.net/codrops/collective/

**Comment by thedaviddias** [comment]
Of course! Above all, I can't be enough thankful to put my 2 projects on your last Collective #359! You want me to add it or do you want to do a PR @botelho?

**Comment by botelho** [comment]
No problem, two great projects! 
I noticed that Codrops was already added to the "Aggregators / News" section which makes more sense since we don't actually have a newsletter :) So maybe we could leave it as it is. Thanks and all the best!
