### ISSUE TITLE
Reactjs is missing, quite popular now a days with Front End Developers

### ISSUE THREAD

**Issue by vikramvi** [thedaviddias/Resources-Front-End-Beginner#8]

**Comment by thedaviddias** [comment]
Hi @vikramvi, yes Reactjs is... but that checklist is for beginners only. Soon, I'll publish another list with JS frameworks and more. But when you start Front-End Development, I think HTML, CSS and JavaScript are the priority. Don't you think?

**Comment by thedaviddias** [comment]
Yes, it's why I'll launching soon another list to show where beginners need to go 😉
